# Generated by Django 2.0.6 on 2018-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=30, unique=True)),
                ('account_type', models.CharField(choices=[('ST', 'Student'), ('TA', 'Teaching Assistant'), ('PR', 'Professor'), ('AR', 'Administrator')], max_length=2)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('accounts', models.ManyToManyField(to='account.Account')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='majors',
            field=models.ManyToManyField(to='account.Major'),
        ),
    ]
