# Generated by Django 2.0.6 on 2018-07-01 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='college',
            name='majors',
            field=models.ManyToManyField(blank=True, to='account.Major'),
        ),
        migrations.AlterField(
            model_name='major',
            name='accounts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
