# Generated by Django 2.0.6 on 2018-07-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180701_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='majors',
        ),
        migrations.AddField(
            model_name='major',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.College'),
        ),
    ]
