# Generated by Django 2.0 on 2018-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180701_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='college',
        ),
        migrations.AddField(
            model_name='college',
            name='majors',
            field=models.ManyToManyField(blank=True, to='account.Major'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Major'),
        ),
    ]
